name: TEST
on:
  push:
    branches:
    - the-one
    paths:
    - '**.ts'
    - '**.js'
    - '**.json'
    - '.github/workflows/test.yml'
  pull_request:
    branches:
    - the-one
    Paths:
    - '**.ts'
    - '**.js'
    - '**.json'
    - '.github/workflows/test.yml'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 20
        - 21
        - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run language
      - run: npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: unit-test-${{ env.CURRENT_NODE_VERSION }}
  end:
    runs-on: ubuntu-latest
    needs:
    - unit-test
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
